"""
Professional Report Generator Module.

Generates PDF and JSON security reports from scan results.
Uses ReportLab for PDF creation — fully offline, no internet required.

Usage:
    from scanner.report_generator import generate_pdf_report, generate_json_report
"""

import json
import os
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    PageBreak,
    HRFlowable,
    KeepTogether,
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT


# ── Paths ──────────────────────────────────────────────
REPORTS_DIR = os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "..", "reports"
)
os.makedirs(REPORTS_DIR, exist_ok=True)


# ── Enterprise Color Palette ───────────────────────────
PRIMARY_BRAND = colors.HexColor("#1E3A8A")   # Deep Blue
SECONDARY_BG = colors.HexColor("#F8FAFC")
HEADER_BG = colors.HexColor("#1E293B")
ROW_ALT = colors.HexColor("#F1F5F9")
WHITE = colors.white
BLACK = colors.black
LIGHT_GRAY = colors.HexColor("#E2E8F0")
DARK_TEXT = colors.HexColor("#0F172A")
MUTED_TEXT = colors.HexColor("#64748B")

SEV_COLORS = {
    "Critical": colors.HexColor("#DC2626"),  # Red 600
    "High": colors.HexColor("#EF4444"),      # Red 500
    "Medium": colors.HexColor("#F59E0B"),    # Amber 500
    "Low": colors.HexColor("#16A34A"),       # Green 600
}

RISK_COLORS = {
    "High": colors.HexColor("#DC2626"),
    "Medium": colors.HexColor("#F59E0B"),
    "Low": colors.HexColor("#16A34A"),
    "Secure": colors.HexColor("#16A34A"),
    "Outdated": colors.HexColor("#DC2626"),
    "Unknown": colors.HexColor("#94A3B8"),
}


# ── Helper: file name from target ──────────────────────
def _make_filename(target, extension):
    """Generate a safe, timestamped filename."""
    safe_target = target.replace(":", "_").replace("/", "_").replace("\\", "_")
    timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M")
    return f"{safe_target}_{timestamp}.{extension}"


# ── Custom page header / footer ────────────────────────
class _EnterpriseReportTemplate(SimpleDocTemplate):
    """Extends SimpleDocTemplate with branded enterprise header and footer."""

    def __init__(self, filename, scan_target="", **kwargs):
        self.scan_target = scan_target
        super().__init__(filename, **kwargs)

    def beforePage(self):
        """Draw header before every page."""
        canvas = self.canv
        width, height = self.pagesize
        if canvas.getPageNumber() == 1:
            return # No header on cover page

        canvas.saveState()
        canvas.setFont("Helvetica-Bold", 10)
        canvas.setFillColor(PRIMARY_BRAND)
        canvas.drawString(20 * mm, height - 15 * mm, "🛡 Vulnerability Scanner")
        
        canvas.setFont("Helvetica", 8)
        canvas.setFillColor(MUTED_TEXT)
        canvas.drawRightString(width - 20 * mm, height - 15 * mm, "Professional Security Assessment Report")
        
        canvas.setStrokeColor(PRIMARY_BRAND)
        canvas.setLineWidth(1.5)
        canvas.line(20 * mm, height - 18 * mm, width - 20 * mm, height - 18 * mm)
        canvas.restoreState()

    def afterPage(self):
        """Draw footer after every page."""
        canvas = self.canv
        width, height = self.pagesize

        # ── Footer ──
        canvas.saveState()
        canvas.setFont("Helvetica", 7)
        canvas.setFillColor(MUTED_TEXT)

        # Left: branding
        canvas.drawString(20 * mm, 12 * mm, "Confidential | Generated by Vulnerability Scanner")

        # Center: page number
        canvas.drawCentredString(width / 2, 12 * mm, f"Page {canvas.getPageNumber()}")

        # Right: timestamp
        canvas.drawRightString(width - 20 * mm, 12 * mm, f"{datetime.now().strftime('%Y-%m-%d %H:%M')}")

        # Separator line
        canvas.setStrokeColor(LIGHT_GRAY)
        canvas.setLineWidth(0.5)
        canvas.line(20 * mm, 16 * mm, width - 20 * mm, 16 * mm)

        canvas.restoreState()


# ── Custom Styles ──────────────────────────────────────
def _get_styles():
    styles = getSampleStyleSheet()

    styles.add(ParagraphStyle("AppCoverTitle", parent=styles["Title"], fontSize=28, leading=34, textColor=PRIMARY_BRAND, spaceAfter=8, alignment=TA_CENTER, fontName="Helvetica-Bold"))
    styles.add(ParagraphStyle("AppCoverSubtitle", parent=styles["Normal"], fontSize=16, leading=20, textColor=MUTED_TEXT, spaceAfter=40, alignment=TA_CENTER, fontName="Helvetica"))
    styles.add(ParagraphStyle("AppCoverDesc", parent=styles["Normal"], fontSize=11, leading=16, textColor=DARK_TEXT, spaceBefore=40, spaceAfter=40, alignment=TA_CENTER, fontName="Helvetica-Oblique"))
    
    styles.add(ParagraphStyle("AppSectionHead", parent=styles["Heading2"], fontSize=16, leading=20, textColor=PRIMARY_BRAND, spaceBefore=24, spaceAfter=12, fontName="Helvetica-Bold", borderPadding=4, backColor=SECONDARY_BG))
    styles.add(ParagraphStyle("AppSubHead", parent=styles["Heading3"], fontSize=12, leading=16, textColor=HEADER_BG, spaceBefore=12, spaceAfter=6, fontName="Helvetica-Bold"))
    
    styles.add(ParagraphStyle("AppBodyText", parent=styles["Normal"], fontSize=9, leading=14, textColor=DARK_TEXT))
    styles.add(ParagraphStyle("AppBodyBold", parent=styles["Normal"], fontSize=9, leading=14, textColor=DARK_TEXT, fontName="Helvetica-Bold"))
    
    styles.add(ParagraphStyle("AppCellText", parent=styles["Normal"], fontSize=8, leading=11, textColor=DARK_TEXT))
    styles.add(ParagraphStyle("AppCellBold", parent=styles["Normal"], fontSize=8, leading=11, textColor=WHITE, fontName="Helvetica-Bold", alignment=TA_CENTER))
    
    styles.add(ParagraphStyle("AppBadge", parent=styles["Normal"], fontSize=8, leading=10, textColor=WHITE, fontName="Helvetica-Bold", alignment=TA_CENTER))

    return styles


# ── Reusable Component Builders ────────────────────────
def _build_table(headers, rows, col_widths=None):
    """Build a styled enterprise table."""
    styles = _get_styles()
    header_paras = [Paragraph(f"<b>{h}</b>", styles["AppCellBold"]) for h in headers]

    formatted_rows = []
    for row in rows:
        formatted_rows.append([Paragraph(str(cell), styles["AppCellText"]) if not isinstance(cell, Paragraph) else cell for cell in row])

    data = [header_paras] + formatted_rows
    table = Table(data, colWidths=col_widths, repeatRows=1)

    style_cmds = [
        ("BACKGROUND", (0, 0), (-1, 0), HEADER_BG),
        ("TEXTCOLOR", (0, 0), (-1, 0), WHITE),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("ALIGN", (0, 0), (-1, 0), "CENTER"),
        ("TOPPADDING", (0, 0), (-1, 0), 8),
        ("BOTTOMPADDING", (0, 0), (-1, 0), 8),
        ("TOPPADDING", (0, 1), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 1), (-1, -1), 6),
        ("GRID", (0, 0), (-1, -1), 0.5, LIGHT_GRAY),
    ]

    for i in range(1, len(data)):
        if i % 2 == 0:
            style_cmds.append(("BACKGROUND", (0, i), (-1, i), ROW_ALT))

    table.setStyle(TableStyle(style_cmds))
    return table

def _kv_table(pairs, styles, width="100%"):
    """Build a clean key-value table for properties."""
    rows = []
    for k, v in pairs:
        rows.append([Paragraph(f"<b>{k}</b>", styles["AppBodyText"]), Paragraph(str(v), styles["AppBodyText"])])
    
    t = Table(rows, colWidths=["35%", "65%"])
    t.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("LINEBELOW", (0, 0), (-1, -1), 0.5, LIGHT_GRAY),
    ]))
    return t

def _colored_badge(text, color):
    """Return a Paragraph styled as a colored badge."""
    return Paragraph(f'<font color="white"><b> {text} </b></font>', ParagraphStyle("AppBadge", backColor=color, borderPadding=2))

def _status_icon(condition, true_text="✔ Yes", false_text="❌ No", true_color=RISK_COLORS["Low"], false_color=RISK_COLORS["High"]):
    if condition:
        return Paragraph(f'<font color="{true_color}"><b>{true_text}</b></font>', _get_styles()["AppBodyText"])
    return Paragraph(f'<font color="{false_color}"><b>{false_text}</b></font>', _get_styles()["AppBodyText"])


# ══════════════════════════════════════════════════════
#  PDF REPORT GENERATOR
# ══════════════════════════════════════════════════════
def generate_pdf_report(scan_data, scan_time=None):
    if not scan_data or "target" not in scan_data:
        raise ValueError("Invalid scan data: missing 'target' key.")

    target = scan_data["target"]
    filename = _make_filename(target, "pdf")
    filepath = os.path.join(REPORTS_DIR, filename)

    styles = _get_styles()
    page_w, page_h = A4
    usable_width = page_w - 40 * mm

    doc = _EnterpriseReportTemplate(
        filepath,
        scan_target=target,
        pagesize=A4,
        topMargin=25 * mm,
        bottomMargin=20 * mm,
        leftMargin=20 * mm,
        rightMargin=20 * mm,
    )

    elements = []

    # ── Derived Data & Risk Scoring ────────────────────
    scan_mode = scan_data.get("scan_mode", "full").capitalize()
    ports = scan_data.get("ports", [])
    va = scan_data.get("version_assessment", {})
    cve = scan_data.get("cve_analysis", {})
    web = scan_data.get("web_security", None)

    risks = []
    if web and web.get("risk_level"): risks.append(web["risk_level"])
    if va.get("overall_risk") and va["overall_risk"] != "Unknown": risks.append(va["overall_risk"])
    if cve.get("highest_severity") and cve["highest_severity"] != "None":
        risks.append("High" if cve["highest_severity"] == "Critical" else cve["highest_severity"])
    
    if "High" in risks: overall_risk = "High"
    elif "Medium" in risks: overall_risk = "Medium"
    elif "Low" in risks: overall_risk = "Low"
    else: overall_risk = "Unknown"

    # Calculate mock security score out of 100
    score = 100
    score -= cve.get("summary", {}).get("critical", 0) * 15
    score -= cve.get("summary", {}).get("high", 0) * 10
    score -= cve.get("summary", {}).get("medium", 0) * 5
    score -= va.get("summary", {}).get("outdated", 0) * 5
    if overall_risk == "High" and score > 60: score = 55
    if overall_risk == "Medium" and score > 80: score = 75
    score = max(0, min(100, score))


    # ── PAGE 1: COVER PAGE ─────────────────────────────
    elements.append(Spacer(1, 40 * mm))
    elements.append(Paragraph("🛡 Vulnerability Scanner", styles["AppCoverTitle"]))
    elements.append(Paragraph("Professional Security Assessment Report", styles["AppCoverSubtitle"]))
    
    elements.append(Paragraph(f"This report summarizes the findings of an automated vulnerability assessment performed using the Vulnerability Scanner platform against the target infrastructure.", styles["AppCoverDesc"]))
    
    cover_data = [
        ("Target", target),
        ("Scan Mode", f"{scan_mode} Scan"),
        ("Scan Date", datetime.now().strftime("%B %d, %Y")),
        ("Scan Duration", f"{scan_time} seconds" if scan_time else "N/A"),
        ("Overall Risk", _colored_badge(overall_risk, RISK_COLORS.get(overall_risk, MUTED_TEXT))),
        ("Report Version", "v1.0 (Final)"),
        ("Generated By", "Vulnerability Scanner Automated Engine"),
    ]
    elements.append(_kv_table(cover_data, styles))
    elements.append(PageBreak())


    # ── PAGE 2: EXECUTIVE SUMMARY ──────────────────────
    elements.append(Paragraph("1. Executive Summary", styles["AppSectionHead"]))
    
    # Dashboard summary block via Table
    summary_data = [
        ["Open Ports", "Services", "Software", "Total CVEs", "Score"],
        [
            Paragraph(f'<b><font size=18>{len(ports)}</font></b>', styles["AppCoverSubtitle"]),
            Paragraph(f'<b><font size=18>{len(set(p.get("service") for p in ports if p.get("service")))}</font></b>', styles["AppCoverSubtitle"]),
            Paragraph(f'<b><font size=18>{va.get("summary", {}).get("total", 0)}</font></b>', styles["AppCoverSubtitle"]),
            Paragraph(f'<b><font size=18 color="{RISK_COLORS["High"]}">{cve.get("summary", {}).get("total_cves", 0)}</font></b>', styles["AppCoverSubtitle"]),
            Paragraph(f'<b><font size=18 color="{PRIMARY_BRAND}">{score} / 100</font></b>', styles["AppCoverSubtitle"]),
        ]
    ]
    t = Table(summary_data, colWidths=[usable_width/5]*5)
    t.setStyle(TableStyle([
        ("ALIGN", (0,0), (-1,-1), "CENTER"),
        ("BACKGROUND", (0,0), (-1,-1), SECONDARY_BG),
        ("BOX", (0,0), (-1,-1), 1, LIGHT_GRAY),
        ("GRID", (0,0), (-1,-1), 1, LIGHT_GRAY),
        ("TOPPADDING", (0,0), (-1,-1), 10),
        ("BOTTOMPADDING", (0,0), (-1,-1), 10),
    ]))
    elements.append(t)
    elements.append(Spacer(1, 10*mm))


    # ── 2. PORT SCAN SECTION ───────────────────────────
    elements.append(Paragraph("2. Port Scan Results", styles["AppSectionHead"]))
    if ports:
        va_map = {a["product"]: a for a in va.get("assessments", [])}
        headers = ["Port", "State", "Service", "Product", "Version", "Latest", "Status", "Risk"]
        rows = []
        for p in ports:
            a = va_map.get(p.get("product", ""))
            rows.append([
                str(p.get("port", "")),
                _colored_badge(p.get("state", "").upper(), RISK_COLORS["Secure"] if p.get("state")=="open" else MUTED_TEXT),
                p.get("service", ""),
                p.get("product", "Unknown"),
                p.get("version", "Unknown"),
                a["latest_version"] if a else "—",
                _colored_badge(a["status"], RISK_COLORS.get(a["status"], MUTED_TEXT)) if a else "—",
                _colored_badge(a["risk"], RISK_COLORS.get(a["risk"], MUTED_TEXT)) if a else "—",
            ])
        col_w = [usable_width * 0.08, usable_width * 0.1, usable_width * 0.1, usable_width * 0.2, usable_width * 0.12, usable_width * 0.12, usable_width * 0.14, usable_width * 0.14]
        elements.append(_build_table(headers, rows, col_w))
    else:
        elements.append(Paragraph("No open ports detected.", styles["AppBodyText"]))


    # ── 3. WEB SECURITY SECTION ────────────────────────
    elements.append(Paragraph("3. Web Security Analysis", styles["AppSectionHead"]))
    if web:
        sec_pairs = [
            ("HTTPS Available", _status_icon(web.get("https_available"), "✔ Enabled", "❌ Not Enabled")),
            ("HTTP → HTTPS Redirect", _status_icon(web.get("redirects_to_https"), "✔ Yes", "❌ No")),
            ("Server Version", _status_icon(not web.get("server_version_exposed"), "✔ Hidden", "⚠️ Exposed", false_color=RISK_COLORS["Medium"])),
            ("Risk Level", _colored_badge(web.get("risk_level", "N/A"), RISK_COLORS.get(web.get("risk_level", "N/A"), MUTED_TEXT))),
        ]
        elements.append(_kv_table(sec_pairs, styles))
        
        headers_dict = web.get("headers", {})
        if headers_dict:
            elements.append(Paragraph("Security Headers Validation", styles["AppSubHead"]))
            h_rows = []
            for h_name, h_val in headers_dict.items():
                h_rows.append([
                    Paragraph(h_name, styles["AppBodyText"]),
                    _status_icon(h_val != "Missing", "✔ Present", "❌ Missing")
                ])
            elements.append(_build_table(["Header", "Status"], h_rows, [usable_width*0.7, usable_width*0.3]))
    else:
        elements.append(Paragraph("Web security analysis not applicable or not performed.", styles["AppBodyText"]))


    # ── 4. SOFTWARE ASSESSMENT ─────────────────────────
    elements.append(Paragraph("4. Software Assessment", styles["AppSectionHead"]))
    assessments = va.get("assessments", [])
    if assessments:
        sa_rows = []
        for a in assessments:
            sa_rows.append([
                Paragraph(a.get("product", ""), styles["AppBodyBold"]),
                a.get("detected_version", ""),
                a.get("latest_version", ""),
                a.get("minimum_secure", ""),
                _colored_badge(a.get("status", ""), RISK_COLORS.get(a.get("status", ""), MUTED_TEXT))
            ])
        elements.append(_build_table(["Product", "Detected", "Latest", "Min Secure", "Status"], sa_rows, [usable_width*0.25, usable_width*0.15, usable_width*0.15, usable_width*0.2, usable_width*0.25]))
    else:
        elements.append(Paragraph("No software assessment data available.", styles["AppBodyText"]))


    # ── 5. CVE ANALYSIS ────────────────────────────────
    elements.append(PageBreak())
    elements.append(Paragraph("5. CVE Analysis", styles["AppSectionHead"]))
    findings = cve.get("findings", [])
    if findings:
        for finding in findings:
            elements.append(Paragraph(f"Product: {finding.get('product')} v{finding.get('version')}", styles["AppSubHead"]))
            for c in finding.get("cves", []):
                sev = c.get("severity", "Unknown")
                cve_data = [
                    ["CVE ID", Paragraph(c.get("id", ""), styles["AppBodyBold"]), "Severity", _colored_badge(sev, SEV_COLORS.get(sev, MUTED_TEXT))],
                    ["Description", Paragraph(c.get("description", ""), styles["AppBodyText"]), "", ""],
                    ["Recommendation", Paragraph(c.get("recommendation", ""), styles["AppBodyText"]), "", ""]
                ]
                t = Table(cve_data, colWidths=[usable_width*0.2, usable_width*0.4, usable_width*0.15, usable_width*0.25])
                t.setStyle(TableStyle([
                    ("VALIGN", (0,0), (-1,-1), "TOP"),
                    ("SPAN", (1,1), (-1,1)),
                    ("SPAN", (1,2), (-1,2)),
                    ("BACKGROUND", (0,0), (0,-1), SECONDARY_BG),
                    ("BACKGROUND", (2,0), (2,0), SECONDARY_BG),
                    ("BOX", (0,0), (-1,-1), 1, LIGHT_GRAY),
                    ("GRID", (0,0), (-1,-1), 0.5, LIGHT_GRAY),
                    ("BOTTOMPADDING", (0,0), (-1,-1), 8),
                ]))
                elements.append(KeepTogether(t))
                elements.append(Spacer(1, 5*mm))
    else:
        elements.append(Paragraph("No known CVEs found for the detected software versions.", styles["AppBodyText"]))


    # ── 6. RECOMMENDATIONS ─────────────────────────────
    elements.append(PageBreak())
    elements.append(Paragraph("6. Remediation Recommendations", styles["AppSectionHead"]))
    recs = va.get("recommendations", [])
    if recs:
        for rec in recs:
            # Simple boxing for recommendations
            r_t = Table([[Paragraph(f"💡 <b>Action Required:</b> {rec}", styles["AppBodyText"])]], colWidths=[usable_width])
            r_t.setStyle(TableStyle([
                ("BACKGROUND", (0,0), (-1,-1), colors.HexColor("#EFF6FF")), # Light blue
                ("BOX", (0,0), (-1,-1), 1, colors.HexColor("#BFDBFE")),
                ("PADDING", (0,0), (-1,-1), 10),
            ]))
            elements.append(KeepTogether(r_t))
            elements.append(Spacer(1, 3*mm))
    else:
        elements.append(Paragraph("No specific recommendations at this time.", styles["AppBodyText"]))


    # ── 7. OFFENSE / ATTACK SCENARIOS ──────────────────
    elements.append(PageBreak())
    elements.append(Paragraph("7. Offense / Simulated Attack Scenarios", styles["AppSectionHead"]))
    offense = scan_data.get("offense", {})
    scenarios = offense.get("scenarios", [])
    if scenarios:
        for sc in scenarios:
            sc_data = [
                ["Scenario", Paragraph(sc.get("name", "Unknown"), styles["AppBodyBold"])],
                ["Likelihood", Paragraph(sc.get("likelihood", "Unknown"), styles["AppBodyText"])],
                ["Impact", Paragraph(sc.get("impact", "Unknown"), styles["AppBodyText"])],
                ["Description", Paragraph(sc.get("description", "Unknown"), styles["AppBodyText"])]
            ]
            t = Table(sc_data, colWidths=[usable_width*0.2, usable_width*0.8])
            t.setStyle(TableStyle([
                ("VALIGN", (0,0), (-1,-1), "TOP"),
                ("BACKGROUND", (0,0), (0,-1), SECONDARY_BG),
                ("BOX", (0,0), (-1,-1), 1, LIGHT_GRAY),
                ("GRID", (0,0), (-1,-1), 0.5, LIGHT_GRAY),
            ]))
            elements.append(KeepTogether(t))
            elements.append(Spacer(1, 5*mm))
    else:
        elements.append(Paragraph("No simulated attack scenarios generated.", styles["AppBodyText"]))

    # ── 8. DEFENSE / MONITORING PLAYBOOKS ──────────────
    elements.append(PageBreak())
    elements.append(Paragraph("8. Defense / Monitoring Playbooks", styles["AppSectionHead"]))
    defense = scan_data.get("defense", {})
    playbooks = defense.get("playbooks", [])
    if playbooks:
        for pb in playbooks:
            pb_data = [
                ["Playbook", Paragraph(pb.get("name", "Unknown"), styles["AppBodyBold"])],
                ["Action", Paragraph(pb.get("action", "Unknown"), styles["AppBodyText"])],
                ["Priority", Paragraph(pb.get("priority", "Unknown"), styles["AppBodyText"])]
            ]
            t = Table(pb_data, colWidths=[usable_width*0.2, usable_width*0.8])
            t.setStyle(TableStyle([
                ("VALIGN", (0,0), (-1,-1), "TOP"),
                ("BACKGROUND", (0,0), (0,-1), SECONDARY_BG),
                ("BOX", (0,0), (-1,-1), 1, LIGHT_GRAY),
                ("GRID", (0,0), (-1,-1), 0.5, LIGHT_GRAY),
            ]))
            elements.append(KeepTogether(t))
            elements.append(Spacer(1, 5*mm))
    else:
        elements.append(Paragraph("No monitoring playbooks generated.", styles["AppBodyText"]))

    # ── 9. FINAL SUMMARY ───────────────────────────────
    elements.append(Paragraph("9. Assessment Summary", styles["AppSectionHead"]))
    
    summary_message = "The assessed target appears secure with no immediate issues identified."
    if overall_risk in ["High", "Medium"]:
        summary_message = "The assessed target contains issues that should be addressed. Immediate remediation of High and Critical findings is strongly recommended."

    elements.append(Paragraph(summary_message, ParagraphStyle("SummaryMsg", parent=styles["AppBodyText"], spaceAfter=15)))

    final_pairs = [
        ("Target", target),
        ("Overall Risk", _colored_badge(overall_risk, RISK_COLORS.get(overall_risk, MUTED_TEXT))),
        ("Security Score", f"{score} / 100"),
        ("Critical Vulnerabilities", cve.get("summary", {}).get("critical", 0)),
        ("High Vulnerabilities", cve.get("summary", {}).get("high", 0)),
        ("Medium Vulnerabilities", cve.get("summary", {}).get("medium", 0)),
    ]
    elements.append(_kv_table(final_pairs, styles))


    # ── Build PDF ──────────────────────────────────────
    doc.build(elements)

    return filepath

# ══════════════════════════════════════════════════════
#  JSON REPORT GENERATOR
# ══════════════════════════════════════════════════════
def generate_json_report(scan_data, scan_time=None):
    """
    Generate a JSON export of the complete scan results.
    """
    if not scan_data or "target" not in scan_data:
        raise ValueError("Invalid scan data: missing 'target' key.")

    target = scan_data["target"]
    filename = _make_filename(target, "json")
    filepath = os.path.join(REPORTS_DIR, filename)

    report = {
        "report_metadata": {
            "generated_at": datetime.now().isoformat(),
            "generator": "Vulnerability Scanner Automated Engine",
            "report_version": "1.0",
        },
        "scan_info": {
            "target": target,
            "scan_mode": scan_data.get("scan_mode", "full"),
            "scan_duration": f"{scan_time}s" if scan_time else "N/A",
        },
        "port_scan": scan_data.get("ports", []),
        "web_security": scan_data.get("web_security", None),
        "version_assessment": scan_data.get("version_assessment", {}),
        "cve_analysis": scan_data.get("cve_analysis", {}),
        "recommendations": scan_data.get("version_assessment", {}).get("recommendations", []),
    }

    with open(filepath, "w", encoding="utf-8") as f:
        json.dump(report, f, indent=2, ensure_ascii=False)

    return filepath
